pipewire migrated from libopenaptx to libfreeaptx

diff --git a/pipewire/PKGBUILD b/pipewire/PKGBUILD
--- a/pipewire/PKGBUILD
+++ b/pipewire/PKGBUILD
@@ -3,7 +3,7 @@ pkgname=(pipewire+clang alsa-card-profiles+clang pipewire-docs+clang pipewire-me
   pipewire-alsa+clang pipewire-jack+clang pipewire-pulse+clang gst-plugin-pipewire+clang
   pipewire-zeroconf+clang)
 pkgver=0.3.32
-pkgrel=1
+pkgrel=2
 epoch=1
 pkgdesc="Low-latency audio/video router and processor"
 url="https://pipewire.org"
@@ -11,7 +11,7 @@ license=(MIT)
 arch=(x86_64)
 makedepends=(git meson doxygen xmltoman valgrind libpulse alsa-lib libusb
   gst-plugins-base rtkit dbus sdl2 ncurses libsndfile bluez-libs sbc
-  libldac libopenaptx libfdk-aac avahi webrtc-audio-processing)
+  libldac libfreeaptx libfdk-aac avahi webrtc-audio-processing)
 checkdepends=(desktop-file-utils)
 _commit=41ce3092756ab27106881f4246e54bf32ea5adbe # tags/0.3.32
 source=("git+https://gitlab.freedesktop.org/pipewire/pipewire.git#commit=${_commit}")
@@ -24,6 +24,13 @@ prepare() {
   if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
     _extra_lto_flag='-D b_lto_mode=thin'
   fi
+
+  cd "${srcdir:?}/pipewire" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/pipewire directory! Prepare Failed! \E[0m"
+    exit 1
+  )
+
+  git cherry-pick -n 1216371f8c06f548f8ade6468b66612f43df1436
 
 }
 
@@ -85,7 +92,7 @@ package_pipewire+clang() {
   license+=(LGPL) # libspa-alsa
   depends=(rtkit alsa-card-profiles libdbus-1.so libncursesw.so libsndfile.so
     libudev.so libusb-1.0.so libasound.so libsystemd.so libbluetooth.so
-    libsbc.so libldacBT_enc.so libopenaptx.so libfdk-aac.so
+    libsbc.so libldacBT_enc.so libfreeaptx.so libfdk-aac.so
     libwebrtc_audio_processing.so)
   optdepends=('pipewire-docs: Documentation'
     'pipewire-media-session: Default session manager'
