Format PGP Keys

diff --git a/xorg-xauth/PKGBUILD b/xorg-xauth/PKGBUILD
--- a/xorg-xauth/PKGBUILD
+++ b/xorg-xauth/PKGBUILD
@@ -12,55 +12,57 @@ makedepends=('xorg-util-macros')
 groups=('xorg-apps' 'xorg')
 source=("${url}/releases/individual/app/xauth-${pkgver}.tar.bz2"{,.sig})
 sha512sums=('b6ecd59a853a491ef45bf8cfbff63bed36645f81cb79ae9d18458b57f7502bccf92f0d979d3337578518646f680ad379e67b1dac15a927cbb11372733e7a3a0c'
-    'SKIP')
-validpgpkeys=('3BB639E56F861FA2E86505690FDD682D974CA72A')
-validpgpkeys+=('995ED5C8A6138EB0961F18474C09DD83CAAA50B2') # "Adam Jackson <ajax@nwnk.net>"
+  'SKIP')
+validpgpkeys=(
+  '3BB639E56F861FA2E86505690FDD682D974CA72A'
+  '995ED5C8A6138EB0961F18474C09DD83CAAA50B2' # "Adam Jackson <ajax@nwnk.net>"
+)
 
 _llvm=0
 
 prepare() {
 
-    if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
-        _llvm=1
-    fi
+  if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
+    _llvm=1
+  fi
 
 }
 
 build() {
 
-    cd "${srcdir:?}/xauth-${pkgver}" || (
-        echo -e "\E[1;31mCan't cd to ${srcdir:?}/xauth-${pkgver} directory! Build Failed! \E[0m"
-        exit 1
-    )
+  cd "${srcdir:?}/xauth-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/xauth-${pkgver} directory! Build Failed! \E[0m"
+    exit 1
+  )
 
-    if [[ ${_llvm} -eq 1 ]]; then
+  if [[ ${_llvm} -eq 1 ]]; then
 
-        CFLAGS="${CFLAGS} -flto=thin" CXXFLAGS="${CXXFLAGS} -flto=thin" \
-            ./configure \
-            --prefix=/usr
+    CFLAGS="${CFLAGS} -flto=thin" CXXFLAGS="${CXXFLAGS} -flto=thin" \
+      ./configure \
+      --prefix=/usr
 
-        CFLAGS="${CFLAGS} -flto=thin" CXXFLAGS="${CXXFLAGS} -flto=thin" make
+    CFLAGS="${CFLAGS} -flto=thin" CXXFLAGS="${CXXFLAGS} -flto=thin" make
 
-    else
+  else
 
-        ./configure \
-            --prefix=/usr
+    ./configure \
+      --prefix=/usr
 
-        make
+    make
 
-    fi
+  fi
 
 }
 
 package() {
 
-    cd "${srcdir:?}/xauth-${pkgver}" || (
-        echo -e "\E[1;31mCan't cd to ${srcdir:?}/xauth-${pkgver} directory! Package Failed! \E[0m"
-        exit 1
-    )
+  cd "${srcdir:?}/xauth-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/xauth-${pkgver} directory! Package Failed! \E[0m"
+    exit 1
+  )
 
-    make DESTDIR="${pkgdir:?}" install
-    install -d -m755 "${pkgdir:?}/usr/share/licenses/${pkgname}"
-    install -m644 COPYING "${pkgdir:?}/usr/share/licenses/${pkgname}/"
+  make DESTDIR="${pkgdir:?}" install
+  install -d -m755 "${pkgdir:?}/usr/share/licenses/${pkgname}"
+  install -m644 COPYING "${pkgdir:?}/usr/share/licenses/${pkgname}/"
 
 }
