Packages update

diff --git a/pango/PKGBUILD b/pango/PKGBUILD
--- a/pango/PKGBUILD
+++ b/pango/PKGBUILD
@@ -1,7 +1,7 @@
 pkgbase=pango+clang
 pkgname=(pango+clang pango-docs+clang)
 pkgver=1.48.9
-pkgrel=1
+pkgrel=2
 epoch=1
 pkgdesc="A library for layout and rendering of text"
 url="https://www.pango.org/"
@@ -23,6 +23,14 @@ prepare() {
   if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
     _extra_lto_flag='-D b_lto_mode=thin'
   fi
+
+  cd "${srcdir:?}/pango" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/pango directory! Prepare Failed! \E[0m"
+    exit 1
+  )
+
+  # https://gitlab.gnome.org/GNOME/pango/-/issues/599
+  git cherry-pick -n b823774b132e1cddd6e4a8a423761c5c15375753
 
 }
 
