Update mesa, pango, fontconfig

diff --git a/pango/PKGBUILD b/pango/PKGBUILD
--- a/pango/PKGBUILD
+++ b/pango/PKGBUILD
@@ -1,6 +1,6 @@
 pkgbase=pango+clang
 pkgname=(pango+clang pango-docs+clang)
-pkgver=1.48.5+24+g07f64620
+pkgver=1.48.6
 pkgrel=1
 epoch=1
 pkgdesc="A library for layout and rendering of text"
@@ -10,9 +10,15 @@ license=(LGPL)
 depends=(libthai cairo libxft harfbuzz fribidi)
 makedepends=(gobject-introspection help2man git meson gi-docgen)
 checkdepends=(ttf-dejavu cantarell-fonts noto-fonts noto-fonts-emoji)
-_commit=07f646202ee9d54e5884e8e7ae5e0eab621b43bd
-source=("git+https://gitlab.gnome.org/GNOME/pango.git#commit=$_commit")
-sha256sums=('SKIP')
+_commit=61763238b548d717d0772f31467ad7e9b6a557ae
+source=(
+  "git+https://gitlab.gnome.org/GNOME/pango.git#commit=${_commit}"
+  "0001-fix-test.patch"
+)
+sha256sums=(
+  'SKIP'
+  'd74df5b325007d02c3054a9e2a623327d0d195adf18d0ee41689672c27657cdb'
+)
 
 _extra_lto_flag=""
 
@@ -21,6 +27,17 @@ prepare() {
   if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
     _extra_lto_flag='-D b_lto_mode=thin'
   fi
+
+  cd "${srcdir:?}/pango" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/pango directory! Prepare Failed! \E[0m"
+    exit 1
+  )
+
+  git apply -3 ../0001-fix-test.patch
+
+}
+
+pkgver() {
 
   cd "${srcdir:?}/pango" || (
     echo -e "\E[1;31mCan't cd to ${srcdir:?}/pango directory! PkgVer Failed! \E[0m"
