Update packages

diff --git a/polkit/PKGBUILD b/polkit/PKGBUILD
--- a/polkit/PKGBUILD
+++ b/polkit/PKGBUILD
@@ -1,6 +1,6 @@
 pkgname=polkit+clang
 pkgver=0.120
-pkgrel=3
+pkgrel=4
 pkgdesc="Application development toolkit for controlling system-wide privileges"
 arch=(x86_64)
 license=(LGPL)
@@ -12,8 +12,12 @@ makedepends=(meson gtk-doc gobject-introspection git)
 checkdepends=(python-dbusmock)
 backup=(etc/pam.d/polkit-1)
 _commit=92b910ce2273daf6a76038f6bd764fa6958d4e8e
-source=("git+https://gitlab.freedesktop.org/polkit/polkit.git#commit=${_commit}")
-sha256sums=('SKIP')
+source=(
+  "git+https://gitlab.freedesktop.org/polkit/polkit.git#commit=${_commit}"
+  meson-0.61.diff
+)
+sha256sums=('SKIP'
+  '45d08bbb76e1e22ca8e698df04652b7aceaded34f9b76ce6b68152fb26b0de8d')
 
 _llvm=0
 
@@ -35,6 +39,17 @@ prepare() {
   if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
     _extra_lto_flag='-D b_lto_mode=thin'
   fi
+
+  cd "${srcdir:?}/polkit" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/polkit directory! Prepare Failed! \E[0m"
+    exit 1
+  )
+
+  # CVE-2021-4034
+  git cherry-pick -n a2bf5c9c83b6ae46cbd5c779d3055bff81ded683
+
+  # Fix build with Meson 0.61.0
+  git apply -3 "${srcdir:?}/meson-0.61.diff"
 
 }
 
