Update packages

diff --git a/jack2/PKGBUILD b/jack2/PKGBUILD
--- a/jack2/PKGBUILD
+++ b/jack2/PKGBUILD
@@ -1,16 +1,15 @@
 pkgbase=jack2+clang
-pkgname=('jack2+clang' 'jack2-dbus+clang')
+pkgname=('jack2+clang' 'jack2-dbus+clang' 'jack2-docs+clang')
 pkgdesc="The JACK low-latency audio server"
-pkgver=1.9.19
-pkgrel=2
+pkgver=1.9.20
+pkgrel=3
 arch=('x86_64')
 url="https://github.com/jackaudio/jack2"
 license=('GPL2' 'LGPL2.1')
-makedepends=('alsa-lib' 'celt' 'dbus' 'expat' 'git' 'libffado' 'libsamplerate'
-  'libsndfile' 'zita-alsa-pcmi' 'zita-resampler' 'readline' 'systemd' 'waf')
+makedepends=(alsa-lib dbus doxygen expat git libffado libsamplerate opus systemd waf)
 source=("jack2::git+https://github.com/jackaudio/jack2.git#tag=v${pkgver}")
 validpgpkeys=('62B11043D2F6EB6672D93103CDBAA37ABC74FBA0') # falkTX <falktx@falktx.com>
-sha512sums=('SKIP')
+sha256sums=('SKIP')
 
 _llvm=0
 
@@ -29,14 +28,20 @@ prepare() {
   # wscript
   (
     touch __init__.py
-    mkdir -vp tools
-    cp -v waflib/extras/xcode*.py tools
     rm -rv waflib
-    sed -e "s/load('xcode'/load('xcode', tooldir='tools'/g" \
-      -e "s/load('xcode6'/load('xcode6', tooldir='tools'/g" \
-      -i wscript
   )
 
+}
+
+_pick() {
+  local p="$1" f d
+  shift
+  for f; do
+    d="$srcdir/$p/${f#$pkgdir/}"
+    mkdir -p "$(dirname "$d")"
+    mv "$f" "$d"
+    rmdir -p --ignore-fail-on-non-empty "$(dirname "$f")"
+  done
 }
 
 build() {
@@ -56,9 +61,12 @@ build() {
 
   export LINKFLAGS="${LDFLAGS}"
   export PYTHONPATH="${PWD}:${PYTHONPATH}"
+
   waf configure --prefix=/usr \
-    --htmldir="/usr/share/doc/${pkgbase}/" \
+    --htmldir="/usr/share/doc/${pkgbase}/html" \
     --autostart=none \
+    --doxygen=yes \
+    --example-tools=no \
     --systemd-unit \
     --classic \
     --dbus
@@ -69,14 +77,19 @@ build() {
 
 package_jack2+clang() {
 
-  depends=('db' 'gcc-libs' 'glibc' 'opus' 'libasound.so' 'libcelt0.so'
-    'libdbus-1.so' 'libreadline.so' 'libsamplerate.so' 'libsndfile.so'
-    'libsystemd.so' 'libzita-alsa-pcmi.so' 'libzita-resampler.so')
-  optdepends=('a2jmidid: for ALSA MIDI to JACK MIDI bridging'
+  license+=(LGPL2.1)
+  depends=(db gcc-libs glibc opus libasound.so libdbus-1.so libsamplerate.so
+    libsystemd.so)
+  optdepends=(
+    'a2jmidid: for ALSA MIDI to JACK MIDI bridging'
     'libffado: for firewire support using FFADO'
+    'jack-example-tools: for official JACK example-clients and tools'
     'jack2-dbus: for dbus integration'
+    'jack2-docs: for developer documentation'
     'realtime-privileges: for realtime privileges'
-    'zita-ajbridge: for using multiple ALSA devices')
+    'zita-ajbridge: for using multiple ALSA devices'
+  )
+
   provides=('jack' 'jack2' "jack2=${pkgver}" 'libjack.so' 'libjacknet.so' 'libjackserver.so')
   conflicts=('jack' 'jack2')
 
@@ -87,37 +100,35 @@ package_jack2+clang() {
 
   export PYTHONPATH="${PWD}:${PYTHONPATH}"
   waf install --destdir="${pkgdir:?}"
-  rm -rfv "${pkgdir:?}/usr/bin/jack"{dbus,_control} "${pkgdir:?}/usr/share/dbus-1/"
+
+  cd "${pkgdir:?}" || (
+    echo -e "\E[1;31mCan't cd to ${pkgdir:?} directory! Package jack2 Failed! \E[0m"
+    exit 1
+  )
+
+  _pick jack2-dbus usr/bin/jack{dbus,_control}
+  _pick jack2-dbus usr/share/dbus-1/services/*
+  _pick jack2-docs usr/share/doc/${pkgbase}/html
 
 }
 
 package_jack2-dbus+clang() {
 
-  local _names=('alias' 'bufsize' 'connect' 'cpu' 'cpu_load' 'disconnect'
-    'evmon' 'freewheel' 'iodelay' 'latent_client' 'load' 'lsp' 'metro'
-    'midi_dump' 'midi_latency_test' 'midiseq' 'midisine' 'monitor_client'
-    'multiple_metro' 'net_master' 'net_slave' 'netsource' 'property' 'rec'
-    'samplerate' 'server_control' 'session_notify' 'showtime' 'simdtests'
-    'simple_client' 'simple_session_client' 'test' 'thru' 'transport' 'unload'
-    'wait' 'zombie')
-
   pkgdesc+=" (dbus integration)"
-  depends=('gcc-libs' 'glibc' "jack2+clang=${pkgver}" 'libdbus-1.so' 'libjackserver.so'
+  depends=('gcc-libs' 'glibc' "jack2+clang=${pkgver}" libexpat.so 'libdbus-1.so' 'libjackserver.so'
     'python-dbus')
   provides=('jack2-dbus' "jack2-dbus=${pkgver}")
   conflicts=('jack2-dbus')
 
-  cd "${srcdir:?}/jack2" || (
-    echo -e "\E[1;31mCan't cd to ${srcdir:?}/jack2 directory! Package jack2-dbus Failed! \E[0m"
-    exit 1
-  )
+  mv -v jack2-dbus/* "${pkgdir:?}"
 
-  export PYTHONPATH="${PWD}:${PYTHONPATH}"
-  waf install --destdir="${pkgdir:?}"
-  rm -rfv "${pkgdir:?}/etc/" "${pkgdir:?}/usr/include/" "${pkgdir:?}/usr/lib/" \
-    "${pkgdir:?}/usr/share/man/" "${pkgdir:?}/usr/bin/alsa"* "${pkgdir:?}/usr/bin/jackd"
-  for _name in "${_names[@]}"; do
-    rm -v "${pkgdir:?}/usr/bin/jack_${_name}"
-  done
+}
+
+package_jack2-docs+clang() {
+
+  pkgdesc+=" (documentation)"
+  conflicts=('jack2-docs')
+
+  mv -v jack2-docs/* "${pkgdir:?}"
 
 }
