Update Qt to 5.15.3

diff --git a/qt5-declarative/PKGBUILD b/qt5-declarative/PKGBUILD
--- a/qt5-declarative/PKGBUILD
+++ b/qt5-declarative/PKGBUILD
@@ -1,25 +1,27 @@
-pkgname=qt5-wayland+clang
-pkgver=5.15.3+kde+r40
+pkgname=qt5-declarative+clang
+pkgver=5.15.3+kde+r20
 pkgrel=1
 arch=('x86_64')
 url='https://www.qt.io'
 license=('GPL3' 'LGPL3' 'FDL' 'custom')
-provides=("qt5-wayland" "qt5-wayland=${pkgver}")
-conflicts=("qt5-wayland")
-pkgdesc='Provides APIs for Wayland'
-depends=('qt5-declarative' 'libxcomposite')
-makedepends=('vulkan-headers' 'git')
+pkgdesc='Classes for QML and JavaScript languages'
+provides=("qt5-declarative" "qt5-declarative=${pkgver}")
+depends=('qt5-base')
+makedepends=('python' 'vulkan-headers' 'git')
 groups=('qt' 'qt5')
-_commit=118674630cdb5933e66a8b4415afe7c716ad4662
-source=("git+https://invent.kde.org/qt/qt/qtwayland#commit=${_commit}")
+conflicts=('qtchooser' 'qt5-declarative')
+_commit=02105099301450c890e1caba977ef44efdc43da7
+source=(
+  "git+https://invent.kde.org/qt/qt/qtdeclarative#commit=${_commit}"
+)
 sha256sums=('SKIP')
 
 _llvm=0
 
 pkgver() {
 
-  cd "${srcdir:?}/qtwayland" || (
-    echo -e "\E[1;31mCan't cd to ${srcdir:?}/qtwayland directory! PkgVer Failed! \E[0m"
+  cd "${srcdir:?}/qtdeclarative" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/qtdeclarative directory! PkgVer Failed! \E[0m"
     exit 1
   )
 
@@ -48,29 +50,30 @@ build() {
 
   if [[ ${_llvm} -eq 1 ]]; then
 
-    qmake ../qtwayland
     CFLAGS="${CFLAGS} -flto=thin"
     CXXFLAGS="${CXXFLAGS} -flto=thin"
     LDFLAGS="${LDFLAGS} -fuse-ld=lld"
-    make
-
-  else
-
-    qmake ../qtwayland
-    make
 
   fi
+
+  qmake ../qtdeclarative
+  make
 
 }
 
 package() {
 
   cd "${srcdir:?}/build" || (
-    echo -e "\E[1;31mCan't cd to ${srcdir:?}/build directory! Pcakage Failed! \E[0m"
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/build directory! Package Failed! \E[0m"
     exit 1
   )
 
   make INSTALL_ROOT="${pkgdir:?}" install
+
+  # Symlinks for backwards compatibility
+  for b in "${pkgdir:?}"/usr/bin/*; do
+    ln -s "${b##*/}" "${pkgdir:?}/usr/bin/${b##*/}-qt5"
+  done
 
   # Drop QMAKE_PRL_BUILD_DIR because reference the build dir
   find "${pkgdir:?}/usr/lib" -type f -name '*.prl' \
diff --git a/qt5-imageformats/PKGBUILD b/qt5-imageformats/PKGBUILD
--- a/qt5-imageformats/PKGBUILD
+++ b/qt5-imageformats/PKGBUILD
@@ -1,7 +1,6 @@
 pkgname=qt5-imageformats+clang
-_qtver=5.15.2
-pkgver=${_qtver/-/}
-pkgrel=2
+pkgver=5.15.3+kde+r0
+pkgrel=1
 arch=('x86_64')
 url='https://www.qt.io'
 license=('GPL3' 'LGPL3' 'FDL' 'custom')
@@ -9,12 +8,24 @@ provides=("qt5-imageformats" "qt5-imageformats=${pkgver}")
 conflicts=("qt5-imageformats")
 pkgdesc='Plugins for additional image formats: TIFF, MNG, TGA, WBMP'
 depends=('qt5-base' 'jasper' 'libmng' 'libwebp')
-makedepends=()
+makedepends=('git')
 groups=('qt' 'qt5')
-source=("https://download.qt.io/official_releases/qt/${pkgver%.*}/${_qtver}/submodules/qtimageformats-everywhere-src-${_qtver}.tar.xz")
-sha256sums=('bf8285c7ce04284527ab823ddc7cf48a1bb79131db3a7127342167f4814253d7')
+_commit=90038c936763645610fe1e5f05cfc025e4d98631
+source=("git+https://invent.kde.org/qt/qt/qtimageformats#commit=${_commit}")
+sha256sums=('SKIP')
 
 _llvm=0
+
+pkgver() {
+
+  cd "${srcdir:?}/qtimageformats" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/qtimageformats directory! PkgVer Failed! \E[0m"
+    exit 1
+  )
+
+  echo "5.15.3+kde+r$(git rev-list --count v5.15.3-lts-lgpl..${_commit})"
+
+}
 
 prepare() {
 
@@ -43,7 +54,7 @@ build() {
 
   fi
 
-  qmake ../qtimageformats-everywhere-src-${_qtver}
+  qmake ../qtimageformats
   make
 
 }
diff --git a/qt5-x11extras/PKGBUILD b/qt5-x11extras/PKGBUILD
--- a/qt5-x11extras/PKGBUILD
+++ b/qt5-x11extras/PKGBUILD
@@ -1,7 +1,6 @@
 pkgname=qt5-x11extras+clang
-_qtver=5.15.2
-pkgver=${_qtver/-/}
-pkgrel=2
+pkgver=5.15.3+kde+r0
+pkgrel=1
 arch=('x86_64')
 url='https://www.qt.io'
 provides=("qt5-x11extras" "qt5-x11extras=${pkgver}")
@@ -9,11 +8,24 @@ conflicts=("qt5-x11extras")
 license=('GPL3' 'LGPL3' 'FDL' 'custom')
 pkgdesc='Provides platform-specific APIs for X11'
 depends=('qt5-base')
+makedepends=('git')
 groups=('qt' 'qt5')
-source=("https://download.qt.io/official_releases/qt/${pkgver%.*}/${_qtver}/submodules/qtx11extras-everywhere-src-${_qtver}.tar.xz")
-sha256sums=('7014702ee9a644a5a93da70848ac47c18851d4f8ed622b29a72eed9282fc6e3e')
+_commit=f628d7a60e45d90a439cb0a393a6229ac6892be5
+source=("git+https://invent.kde.org/qt/qt/qtx11extras#commit=${_commit}")
+sha256sums=('SKIP')
 
 _llvm=0
+
+pkgver() {
+
+  cd "${srcdir:?}/qtx11extras" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/qtx11extras directory! PkgVer Failed! \E[0m"
+    exit 1
+  )
+
+  echo "5.15.3+kde+r$(git rev-list --count v5.15.3-lts-lgpl..${_commit})"
+
+}
 
 prepare() {
 
@@ -42,7 +54,7 @@ build() {
 
   fi
 
-  qmake ../qtx11extras-everywhere-src-${_qtver}
+  qmake ../qtx11extras
   make
 
 }
