Update packages

diff --git a/fontconfig/PKGBUILD b/fontconfig/PKGBUILD
--- a/fontconfig/PKGBUILD
+++ b/fontconfig/PKGBUILD
@@ -1,6 +1,6 @@
 pkgname=fontconfig+clang
 pkgver=2.13.94
-pkgrel=4
+pkgrel=6
 epoch=2
 pkgdesc="Library for configuring and customizing font access"
 url=https://www.freedesktop.org/wiki/Software/fontconfig/
@@ -16,18 +16,23 @@ install=fontconfig.install
 backup=(etc/fonts/fonts.conf)
 _commit=e474b380ffdb330eca7dd0f0fddacc7b19f3247d
 source=(
-  "git+https://gitlab.freedesktop.org/fontconfig/fontconfig.git#commit=${_commit}"
+  #"git+https://gitlab.freedesktop.org/fontconfig/fontconfig.git#commit=${_commit}"
+  "https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/${_commit}/fontconfig-${_commit}.tar.gz"
   40-fontconfig-config.script
   40-fontconfig-config.hook
   fontconfig.hook
+  fontconfig-sleep-less.patch
   fontconfig-meson-add-libxml2-parser.patch
+  fontconfig-improvements.patch
 )
 
-sha256sums=('SKIP'
+sha256sums=('ba33e4aad2d7ed7d489f69d0a83e62ceab2b7b181123e67c1874fcdbde134b31'
   '7a9d50bccc709eb15db6ba8e13f69bc9d79b0bf354f1d17c1a5b2748edff3c33'
   '44f12491c9fd7eff825853846a2b3b8df2b96fc6520be5cb31ce7f37a160ff02'
   'fd7b6ce8ce178107f2e0b52462ebf186b6051c6eec945770107fda57048c9f34'
-  'bbbaf032d175b339fd39647e342d67455cd4a0df5f9435a918f3e758291fb0e6')
+  'b2bee567aab161615cf565a5a426ab2e93ab706f0913d4a3ff94b8f40766b574'
+  'bbbaf032d175b339fd39647e342d67455cd4a0df5f9435a918f3e758291fb0e6'
+  '1fb94b1776f3596265f1c34426e5f61a2b816d81bc097bc7e68dd635023a2bf2')
 
 _extra_lto_flag=""
 
@@ -44,18 +49,20 @@ prepare() {
     _extra_lto_flag='-D b_lto_mode=thin'
   fi
 
-  cd "${srcdir:?}/fontconfig" || (
-    echo -e "\E[1;31mCan't cd to ${srcdir:?}/fontconfig directory! Prepare Failed! \E[0m"
+  cd "${srcdir:?}/fontconfig-${_commit}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/fontconfig-${_commit} directory! Prepare Failed! \E[0m"
     exit 1
   )
 
+  _patch fontconfig-sleep-less.patch
   _patch fontconfig-meson-add-libxml2-parser.patch
+  _patch fontconfig-improvements.patch
 
 }
 
 build() {
 
-  meson setup fontconfig build \
+  meson setup "fontconfig-${_commit}" build \
     --prefix /usr \
     --libexecdir lib \
     --sbindir bin \
@@ -95,6 +102,6 @@ package() {
   install -Dt "${pkgdir:?}/usr/share/libalpm/hooks" -m644 {40-fontconfig-config,fontconfig}.hook
   install -D 40-fontconfig-config.script \
     "${pkgdir:?}/usr/share/libalpm/scripts/40-fontconfig-config"
-  install -Dt "${pkgdir:?}/usr/share/licenses/${pkgname}" -m644 "fontconfig/COPYING"
+  install -Dt "${pkgdir:?}/usr/share/licenses/${pkgname}" -m644 "fontconfig-${_commit}/COPYING"
 
 }
