Update build system

diff --git a/libsm/PKGBUILD b/libsm/PKGBUILD
--- a/libsm/PKGBUILD
+++ b/libsm/PKGBUILD
@@ -16,43 +16,44 @@ _llvm=0
 
 prepare() {
 
-    if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
-        _llvm=1
-    fi
+	if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
+		_llvm=1
+	fi
 
 }
 
 build() {
 
-    cd "${srcdir:?}/libSM-${pkgver}" || (
-        echo -e "\E[1;31mCan't cd to ${srcdir:?}/libSM-${pkgver} directory! Build Failed! \E[0m"
-        exit 1
-    )
+	cd "${srcdir:?}/libSM-${pkgver}" || (
+		echo -e "\E[1;31mCan't cd to ${srcdir:?}/libSM-${pkgver} directory! Build Failed! \E[0m"
+		exit 1
+	)
 
-    if [[ ${_llvm} -eq 1 ]]; then
+	if [[ ${_llvm} -eq 1 ]]; then
 
-        CFLAGS="${CFLAGS} -flto=thin"
-        CXXFLAGS="${CXXFLAGS} -flto=thin"
+		CFLAGS="${CFLAGS} -flto=thin"
+		CXXFLAGS="${CXXFLAGS} -flto=thin"
+		LDFLAGS="${LDFLAGS} -fuse-ld=lld"
 
-    fi
+	fi
 
-    ./configure \
-        --prefix=/usr \
-        --sysconfdir=/etc
+	./configure \
+		--prefix=/usr \
+		--sysconfdir=/etc
 
-    make
+	make
 
 }
 
 package() {
 
-    cd "${srcdir:?}/libSM-${pkgver}" || (
-        echo -e "\E[1;31mCan't cd to ${srcdir:?}/libSM-${pkgver} directory! Package Failed! \E[0m"
-        exit 1
-    )
+	cd "${srcdir:?}/libSM-${pkgver}" || (
+		echo -e "\E[1;31mCan't cd to ${srcdir:?}/libSM-${pkgver} directory! Package Failed! \E[0m"
+		exit 1
+	)
 
-    make DESTDIR="${pkgdir:?}" install
+	make DESTDIR="${pkgdir:?}" install
 
-    install -Dm644 COPYING "${pkgdir:?}/usr/share/licenses/${pkgname}/COPYING"
+	install -Dm644 COPYING "${pkgdir:?}/usr/share/licenses/${pkgname}/COPYING"
 
 }
diff --git a/util-linux/PKGBUILD b/util-linux/PKGBUILD
--- a/util-linux/PKGBUILD
+++ b/util-linux/PKGBUILD
@@ -3,7 +3,7 @@ pkgname=(util-linux+clang util-linux-libs+clang)
 _pkgmajor=2.37
 _realver=${_pkgmajor}.1
 pkgver=${_realver/-/}
-pkgrel=1
+pkgrel=3
 pkgdesc='Miscellaneous system utilities for Linux'
 url='https://github.com/karelzak/util-linux'
 arch=('x86_64')
@@ -11,12 +11,16 @@ makedepends=('asciidoctor' 'libcap-ng' 'libxcrypt' 'python' 'systemd')
 license=('GPL2')
 options=('strip')
 validpgpkeys=('B0C64D14301CC6EFAEDF60E4E4B71D5EEC39C284') # Karel Zak
-source=("https://www.kernel.org/pub/linux/utils/util-linux/v${_pkgmajor}/util-linux-${_realver}.tar."{xz,sign}
+source=(
+  "https://www.kernel.org/pub/linux/utils/util-linux/v${_pkgmajor}/util-linux-${_realver}.tar."{xz,sign}
   pam-{login,common,runuser,su}
   'util-linux.sysusers'
   '60-rfkill.rules'
   'rfkill-unblock_.service'
-  'rfkill-block_.service')
+  'rfkill-block_.service'
+  '0001-sulogin-fix-getpasswd.patch'
+  '0002-libmount-fix-setgroups-use.patch'
+)
 sha256sums=('8e4bd42053b726cf86eb4d13a73bc1d9225a2c2e1a2e0d2a891f1020f83e6b76'
   'SKIP'
   '99cd77f21ee44a0c5e57b0f3670f711a00496f198fc5704d7e44f5d817c81a0f'
@@ -26,7 +30,9 @@ sha256sums=('8e4bd42053b726cf86eb4d13a73bc1d9225a2c2e1a2e0d2a891f1020f83e6b76'
   '10b0505351263a099163c0d928132706e501dd0a008dac2835b052167b14abe3'
   '7423aaaa09fee7f47baa83df9ea6fef525ff9aec395c8cbd9fe848ceb2643f37'
   '8ccec10a22523f6b9d55e0d6cbf91905a39881446710aa083e935e8073323376'
-  'a22e0a037e702170c7d88460cc9c9c2ab1d3e5c54a6985cd4a164ea7beff1b36')
+  'a22e0a037e702170c7d88460cc9c9c2ab1d3e5c54a6985cd4a164ea7beff1b36'
+  '00d526cfaca8979e433c7379c634cf14e700322f0ed0c5a7996af1c900147268'
+  '56fbc491b999aa18113237f28d399045a6d66678353b3619ab8da2f8518d2a4d')
 
 _llvm=0
 
@@ -36,12 +42,20 @@ prepare() {
     _llvm=1
   fi
 
+  cd "${srcdir:?}/util-linux-${_realver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/util-linux-${_realver} directory! Prepare Failed! \E[0m"
+    exit 1
+  )
+
+  patch -Np1 <../0001-sulogin-fix-getpasswd.patch
+  patch -Np1 <../0002-libmount-fix-setgroups-use.patch
+
 }
 
 build() {
 
   cd "${srcdir:?}/util-linux-${_realver}" || (
-    echo -e "\E[1;31mCan't cd to ${srcdir:?}/util-linux-${_realver} directory! Prepare Failed! \E[0m"
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/util-linux-${_realver} directory! Build Failed! \E[0m"
     exit 1
   )
 
@@ -49,6 +63,7 @@ build() {
 
     CFLAGS="${CFLAGS} -flto=thin"
     CXXFLAGS="${CXXFLAGS} -flto=thin"
+    LDFLAGS="${LDFLAGS} -fuse-ld=lld"
 
   fi
 
diff --git a/xorg-setxkbmap/PKGBUILD b/xorg-setxkbmap/PKGBUILD
--- a/xorg-setxkbmap/PKGBUILD
+++ b/xorg-setxkbmap/PKGBUILD
@@ -11,7 +11,7 @@ depends=('libxkbfile')
 makedepends=('xorg-util-macros')
 source=("${url}/releases/individual/app/setxkbmap-${pkgver}.tar.bz2"{,.sig})
 sha512sums=('bfa8015dee0d8d3fdbbd89afbd71c8606ce168d6edca8521d5ed05a00fecbea39bc4bfcce84b71458bdeb34c60bd80a5df27e0691ccee3966443ecdc937faf38'
-    'SKIP')
+  'SKIP')
 validpgpkeys=('4A193C06D35E7C670FA4EF0BA2FB9E081F2D130E') # Alan Coopersmith <alan.coopersmith@oracle.com>
 groups=('xorg-apps' 'xorg')
 
@@ -19,41 +19,42 @@ _llvm=0
 
 prepare() {
 
-    if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
-        _llvm=1
-    fi
+  if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
+    _llvm=1
+  fi
 
 }
 
 build() {
 
-    cd "${srcdir:?}/setxkbmap-${pkgver}" || (
-        echo -e "\E[1;31mCan't cd to ${srcdir:?}/setxkbmap-${pkgver} directory! Build Failed! \E[0m"
-        exit 1
-    )
+  cd "${srcdir:?}/setxkbmap-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/setxkbmap-${pkgver} directory! Build Failed! \E[0m"
+    exit 1
+  )
 
-    if [[ ${_llvm} -eq 1 ]]; then
+  if [[ ${_llvm} -eq 1 ]]; then
 
-        CFLAGS="${CFLAGS} -flto=thin"
-        CXXFLAGS="${CXXFLAGS} -flto=thin"
+    CFLAGS="${CFLAGS} -flto=thin"
+    CXXFLAGS="${CXXFLAGS} -flto=thin"
+    LDFLAGS="${LDFLAGS} -fuse-ld=lld"
 
-    fi
+  fi
 
-    ./configure \
-        --prefix=/usr
+  ./configure \
+    --prefix=/usr
 
-    make
+  make
 
 }
 
 package() {
 
-    cd "${srcdir:?}/setxkbmap-${pkgver}" || (
-        echo -e "\E[1;31mCan't cd to ${srcdir:?}/setxkbmap-${pkgver} directory! Package Failed! \E[0m"
-        exit 1
-    )
+  cd "${srcdir:?}/setxkbmap-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/setxkbmap-${pkgver} directory! Package Failed! \E[0m"
+    exit 1
+  )
 
-    make DESTDIR="${pkgdir:?}" install
-    install -Dm644 COPYING "${pkgdir:?}/usr/share/licenses/${pkgname}/COPYING"
+  make DESTDIR="${pkgdir:?}" install
+  install -Dm644 COPYING "${pkgdir:?}/usr/share/licenses/${pkgname}/COPYING"
 
 }
