Update packages
Add kitty.
Update gtk4, qt5-base, spdlog.

diff --git a/gtk4/PKGBUILD b/gtk4/PKGBUILD
--- a/gtk4/PKGBUILD
+++ b/gtk4/PKGBUILD
@@ -1,7 +1,7 @@
 pkgbase=gtk4+clang
 pkgname=(gtk4+clang gtk-update-icon-cache+clang gtk4-docs+clang gtk4-demos+clang)
 pkgver=4.6.2
-pkgrel=1
+pkgrel=2
 epoch=1
 pkgdesc="GObject-based multi-platform GUI toolkit"
 arch=(x86_64)
@@ -34,6 +34,14 @@ prepare() {
   if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
     _extra_lto_flag='-D b_lto_mode=thin'
   fi
+
+  cd "${srcdir:?}/gtk" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/gtk directory! Prepare Failed! \E[0m"
+    exit 1
+  )
+
+  # https://bugs.archlinux.org/task/74419
+  git cherry-pick -n b67da38916b710ba6eedd65ffb569a29e47ddb4d
 
 }
 
