Update build environment and gtk3.

diff --git a/gtk3/PKGBUILD b/gtk3/PKGBUILD
--- a/gtk3/PKGBUILD
+++ b/gtk3/PKGBUILD
@@ -1,7 +1,7 @@
 pkgbase=gtk3+clang
 pkgname=(gtk3+clang gtk3-docs+clang gtk3-demos+clang)
 pkgver=3.24.33
-pkgrel=2
+pkgrel=3
 epoch=1
 pkgdesc="GObject-based multi-platform GUI toolkit"
 arch=(x86_64)
@@ -22,14 +22,6 @@ sha256sums=('SKIP'
 
 _extra_lto_flag=""
 
-prepare() {
-
-  if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
-    _extra_lto_flag='-D b_lto_mode=thin'
-  fi
-
-}
-
 pkgver() {
 
   cd "${srcdir:?}/gtk" || (
@@ -38,6 +30,25 @@ pkgver() {
   )
 
   git describe --tags | sed 's/[^-]*-g/r&/;s/-/+/g'
+
+}
+
+prepare() {
+
+  if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
+    _extra_lto_flag='-D b_lto_mode=thin'
+  fi
+
+  cd "${srcdir:?}/gtk" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/gtk directory! Prepare Failed! \E[0m"
+    exit 1
+  )
+
+  # Add legacy icons
+  git cherry-pick -n 5a0ffbbb4568e39bdf26006e1bf18c1c1d0d597a
+
+  # Fix annotation
+  git cherry-pick -n 56ada2f01f3b522a42831aba158786e843fca817
 
 }
 
