Update packages

diff --git a/qt5-svg/PKGBUILD b/qt5-svg/PKGBUILD
--- a/qt5-svg/PKGBUILD
+++ b/qt5-svg/PKGBUILD
@@ -48,8 +48,8 @@ prepare() {
 
 build() {
 
-  cd "${srcdir:?}/qtsvg" || (
-    echo -e "\E[1;31mCan't cd to ${srcdir:?}/qtsvg directory! Build Failed! \E[0m"
+  cd "${srcdir:?}/build" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/build directory! Build Failed! \E[0m"
     exit 1
   )
 
@@ -68,8 +68,8 @@ build() {
 
 package() {
 
-  cd "${srcdir:?}/qtsvg" || (
-    echo -e "\E[1;31mCan't cd to ${srcdir:?}/qtsvg directory! Package Failed! \E[0m"
+  cd "${srcdir:?}/build" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/build directory! Package Failed! \E[0m"
     exit 1
   )
 
