Update packages

diff --git a/harfbuzz/PKGBUILD b/harfbuzz/PKGBUILD
--- a/harfbuzz/PKGBUILD
+++ b/harfbuzz/PKGBUILD
@@ -1,6 +1,6 @@
 pkgbase=harfbuzz+clang
 pkgname=(harfbuzz+clang harfbuzz-icu+clang)
-pkgver=4.3.0
+pkgver=4.4.0
 pkgrel=1
 pkgdesc="OpenType text shaping engine"
 url="https://www.freedesktop.org/wiki/Software/HarfBuzz"
@@ -9,7 +9,7 @@ license=(MIT)
 makedepends=(glib2 freetype2 graphite cairo icu gobject-introspection gtk-doc
   ragel git python meson chafa)
 checkdepends=(python-fonttools python-setuptools)
-_commit=aee123fc83388b8f5acfb301d87bd92eccc5b843 # tags/4.3.0^0
+_commit=8537d681728e141550b4470b591fa059f6ca2670 # tags/4.4.0^0
 source=("git+https://github.com/harfbuzz/harfbuzz#commit=${_commit}")
 sha256sums=('SKIP')
 
@@ -31,6 +31,14 @@ prepare() {
   if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
     _extra_lto_flag='-D b_lto_mode=thin'
   fi
+
+  cd "${srcdir:?}/harfbuzz" || (
+    echo -e "\E[1;31mCan't cd to {srcdir:?}/harfbuzz directory! Prepare Failed! \E[0m"
+    exit 1
+  )
+
+  # https://github.com/harfbuzz/harfbuzz/issues/3684
+  git cherry-pick -n 69d53f3e7fde 5da341ce9235
 
 }
 
