Fixed qt5-base bug. Updated packages.

diff --git a/pam/PKGBUILD b/pam/PKGBUILD
--- a/pam/PKGBUILD
+++ b/pam/PKGBUILD
@@ -16,12 +16,13 @@ source=(
 )
 validpgpkeys=(
   '8C6BFD92EE0F42EDF91A6A736D1A7F052E5924BB' # Thorsten Kukuk
-  '296D6F29A020808E8717A8842DB5BD89A340AEB7' #Dimitry V. Levin <ldv@altlinux.org>
+  '296D6F29A020808E8717A8842DB5BD89A340AEB7' # Dimitry V. Levin <ldv@altlinux.org>
 )
 
 sha256sums=('e4ec7131a91da44512574268f493c6d8ca105c87091691b8e9b56ca685d4f94d'
-            'SKIP'
-            '5631f224e90c4f0459361c2a5b250112e3a91ba849754bb6f67d69d683a2e5ac')
+  'SKIP'
+  '5631f224e90c4f0459361c2a5b250112e3a91ba849754bb6f67d69d683a2e5ac'
+)
 
 options=('!emptydirs')
 
@@ -32,6 +33,11 @@ prepare() {
   if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
     _llvm=1
   fi
+
+  cd "${srcdir:?}/Linux-PAM-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir:?}/Linux-PAM-${pkgver} directory! Prepare Failed! \E[0m"
+    exit 1
+  )
 
 }
 
